export interface EcwidCategory {
  id: number;
  name: string;
  seoTitle?: string;
  url: string;
  parentId: number;
  thumbnailUrl?: string;
  imageUrl?: string;
  productCount: number;
  autogeneratedSlug?: string;
  subcategories?: EcwidCategory[];
}

export interface EcwidGalleryImage {
  id: number;
  url: string;
  thumbnail?: string;
  originalImageUrl?: string;
  imageUrl?: string;
  hdThumbnailUrl?: string;
  thumbnailUrl?: string;
  smallThumbnailUrl?: string;
  width?: number;
  height?: number;
  orderBy?: number;
}

export interface EcwidMediaImage {
  id: string;
  isMain?: boolean;
  orderBy?: number;
  image160pxUrl?: string;
  image400pxUrl?: string;
  image800pxUrl?: string;
  image1500pxUrl?: string;
  imageOriginalUrl?: string;
}

export interface EcwidMedia {
  images?: EcwidMediaImage[];
  videos?: unknown[];
}

export interface EcwidProduct {
  id: number;
  name: string;
  description?: string;
  price: number;
  compareToPrice?: number;
  sku: string;
  url: string;
  autogeneratedSlug?: string;
  smallThumbnailUrl?: string;
  hdThumbnailUrl?: string;
  thumbnailUrl?: string;
  imageUrl?: string;
  originalImageUrl?: string;
  galleryImages?: EcwidGalleryImage[];
  media?: EcwidMedia;
  quantity?: number;
  inStock?: boolean;
  categoryIds: number[];
}

export interface EcwidApiResponse<T> {
  items: T[];
  total: number;
  count: number;
  limit: number;
  offset: number;
}

export interface PaginationParams {
  limit?: number;
  offset?: number;
}

export interface FilterParams extends PaginationParams {
  [key: string]: number | string | boolean | undefined;
}
