import { useParams } from 'react-router-dom';
import { Typography } from 'antd';
import { useCategories } from '@entities/category/api/hooks';
import { useProducts } from '@entities/product/api/hooks';
import { AppLayout } from '@widgets/layout/AppLayout';
import { Loader } from '@shared/ui/Loader';
import { Breadcrumbs } from '@shared/ui/Breadcrumbs';
import { useBreadcrumbs } from '@shared/lib/breadcrumbs';
import { ProductsSection } from '@pages/products/ui/ProductsSection';
import { API_LIMITS } from '@shared/config/api';
import { CategoriesSection } from '@pages/products/ui/CategoriesSection';

const { Title } = Typography;

export const ProductsPage = () => {
  const { categorySlug } = useParams<{ categorySlug: string }>();

  const { data: allCategories = [], isLoading: categoriesLoading } = useCategories({
    limit: API_LIMITS.CATEGORIES
  });

  const category = allCategories.find(cat => cat.autogeneratedSlug === categorySlug);

  const categories = category
    ? allCategories.filter(cat => cat.parentId === category.id)
    : allCategories.filter(cat => !cat.parentId);

  const { data: productsData, isLoading: productsLoading } = useProducts({
    category: category?.id,
    limit: API_LIMITS.PRODUCTS,
  });

  const breadcrumbItems = useBreadcrumbs({ category, allCategories });

  return (
    <AppLayout>
      <Title level={1}>
        Catalog{category?.seoTitle && ` - ${category.seoTitle}`}
      </Title>
      {category && <Breadcrumbs items={breadcrumbItems} />}

      {categoriesLoading || productsLoading ? (
        <Loader />
      ) : (
        <>
          <CategoriesSection categories={categories} />
          <ProductsSection products={productsData?.items || []} />
        </>
      )}
    </AppLayout>
  );
};
