import type { EcwidProduct } from '@shared/api/ecwid/types';

export interface CartItem {
  productId: number;
  quantity: number;
}

export type CartProduct = Pick<
  EcwidProduct,
  'id' | 'name' | 'price' | 'autogeneratedSlug' | 'imageUrl' | 'thumbnailUrl' | 'inStock'
>;

export interface CartItemWithProduct extends CartItem {
  product: CartProduct;
}
