import { useMemo } from 'react';
import { ROUTES } from '@shared/config/routes';
import type { BreadcrumbItem } from '@shared/ui/Breadcrumbs/Breadcrumbs';
import type { EcwidCategory } from '@shared/api/ecwid/types';

interface UseBreadcrumbsParams {
  category?: EcwidCategory;
  product?: { name: string };
  allCategories: EcwidCategory[];
}

export const useBreadcrumbs = ({ category, product, allCategories }: UseBreadcrumbsParams): BreadcrumbItem[] => {
  return useMemo(() => {
    const breadcrumbItems: BreadcrumbItem[] = [];

    if (category) {
      const categoriesPath: EcwidCategory[] = [];
      let currentCategory: EcwidCategory | undefined = category;

      while (currentCategory) {
        categoriesPath.unshift(currentCategory);
        const parentId: number = currentCategory.parentId;
        currentCategory = allCategories.find(cat => cat.id === parentId);
      }

      categoriesPath.forEach(categoryItem => {
        breadcrumbItems.push({
          title: categoryItem.name,
          path: ROUTES.CATEGORY(categoryItem.autogeneratedSlug || String(categoryItem.id)),
        });
      });
    }

    if (product) {
      breadcrumbItems.push({ title: product.name });
    }

    return breadcrumbItems;
  }, [category, product, allCategories]);
};

