import { Card, Typography, Image } from 'antd';
import { ROUTES } from '@shared/config/routes';
import type { Category } from '@entities/category/model/types';
import { Link } from 'react-router-dom';
import { StyledTitle } from '@entities/category/ui/CategoryCard/styles';

const { Text } = Typography;

interface CategoryCardProps {
  category: Category;
}

export const CategoryCard = ({ category }: CategoryCardProps) => {
  const imageUrl = category.imageUrl ?? '';

  return (
    <Link to={ROUTES.CATEGORY(category.autogeneratedSlug || String(category.id))}>
      <Card
        hoverable
        cover={imageUrl && <Image src={imageUrl} alt={category.name} preview={false} />}
      >
        <Card.Meta
          title={<StyledTitle level={5}>{category.seoTitle || category.name}</StyledTitle>}
          description={
            category.productCount > 0 && (
              <Text type="secondary">{category.productCount} products</Text>
            )
          }
        />
      </Card>
    </Link>
  );
};
